import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useSettings } from '@/lib/settings'
import { clearAllProgress } from '@/lib/bookState'
import styles from './SettingsScreen.module.css'

export default function SettingsScreen() {
  const settings = useSettings()
  const [cleared, setCleared] = useState(false)
  const [confirmClear, setConfirmClear] = useState(false)

  return (
    <>
      <h1 style={{ marginBlockEnd: 'var(--space-4)' }}>Settings</h1>

      <section className={styles.section} aria-labelledby="s-reading">
        <h2 id="s-reading">Reading</h2>
        <div className={styles.row}>
          <label htmlFor="set-theme">Theme</label>
          <select
            id="set-theme"
            value={settings.theme}
            onChange={(e) =>
              settings.setSetting('theme', e.target.value as 'system' | 'light' | 'dark')
            }
          >
            <option value="system">Match device</option>
            <option value="light">Daytime (light)</option>
            <option value="dark">Bedtime (dark)</option>
          </select>
        </div>
        <div className={styles.row}>
          <label htmlFor="set-size">Story text size</label>
          <select
            id="set-size"
            value={settings.textSize}
            onChange={(e) =>
              settings.setSetting('textSize', e.target.value as 'normal' | 'large' | 'huge')
            }
          >
            <option value="normal">Normal</option>
            <option value="large">Large</option>
            <option value="huge">Extra large</option>
          </select>
        </div>
        <div className={styles.row}>
          <label htmlFor="set-motion">Reduce motion</label>
          <input
            id="set-motion"
            type="checkbox"
            checked={settings.reducedMotion}
            onChange={(e) => settings.setSetting('reducedMotion', e.target.checked)}
          />
        </div>
        <div className={styles.row}>
          <label htmlFor="set-layout">Reader layout</label>
          <select
            id="set-layout"
            value={settings.readerLayout}
            onChange={(e) =>
              settings.setSetting(
                'readerLayout',
                e.target.value as 'auto' | 'single' | 'spread',
              )
            }
          >
            <option value="auto">Automatic</option>
            <option value="single">Always one page</option>
            <option value="spread">Two pages on tablets</option>
          </select>
        </div>
        <div className={styles.row}>
          <label htmlFor="set-swipe">Swipe to turn pages</label>
          <input
            id="set-swipe"
            type="checkbox"
            checked={settings.swipeEnabled}
            onChange={(e) => settings.setSetting('swipeEnabled', e.target.checked)}
          />
        </div>
      </section>

      <section className={styles.section} aria-labelledby="s-narration">
        <h2 id="s-narration">Narration</h2>
        <div className={styles.row}>
          <label htmlFor="set-nar">Preferred narration</label>
          <select
            id="set-nar"
            value={settings.narrationPreference}
            onChange={(e) =>
              settings.setSetting(
                'narrationPreference',
                e.target.value as 'prerecorded' | 'tts' | 'off',
              )
            }
          >
            <option value="prerecorded">Recorded narration when available</option>
            <option value="tts">Device read-aloud voice</option>
            <option value="off">Start silent</option>
          </select>
        </div>
        <div className={styles.row}>
          <label htmlFor="set-auto">Turn pages automatically while narrating</label>
          <input
            id="set-auto"
            type="checkbox"
            checked={settings.narrationAutoAdvance}
            onChange={(e) => settings.setSetting('narrationAutoAdvance', e.target.checked)}
          />
        </div>
        <div className={styles.row}>
          <label htmlFor="set-captions">Show narration captions</label>
          <input
            id="set-captions"
            type="checkbox"
            checked={settings.showCaptions}
            onChange={(e) => settings.setSetting('showCaptions', e.target.checked)}
          />
        </div>
        <p className={styles.note}>
          The device read-aloud voice is generated by this iPhone, iPad or computer. Voice
          choice and speed live in the reader's 🔊 menu.
        </p>
      </section>

      <section className={styles.section} aria-labelledby="s-history">
        <h2 id="s-history">Reading history</h2>
        {confirmClear ? (
          <div className={styles.row}>
            <span className={styles.rowLabel}>Really clear all reading progress?</span>
            <span style={{ display: 'flex', gap: 'var(--space-2)' }}>
              <button
                type="button"
                className="btn btn-danger"
                onClick={() => {
                  void clearAllProgress().then(() => {
                    setCleared(true)
                    setConfirmClear(false)
                  })
                }}
              >
                Yes, clear it
              </button>
              <button type="button" className="btn" onClick={() => setConfirmClear(false)}>
                Keep it
              </button>
            </span>
          </div>
        ) : (
          <div className={styles.row}>
            <span className={styles.rowLabel}>Clear all reading progress</span>
            <button type="button" className="btn btn-outline" onClick={() => setConfirmClear(true)}>
              Clear…
            </button>
          </div>
        )}
        {cleared ? (
          <p role="status" className={styles.note}>
            ✅ Reading progress cleared. Favourites were kept.
          </p>
        ) : null}
        <p className={styles.note}>
          Progress and favourites live only on this device. Individual books can be
          restarted or marked unread from their own page.
        </p>
      </section>

      <section className={styles.section} aria-labelledby="s-more">
        <h2 id="s-more">More</h2>
        <Link className={styles.linkRow} to="/settings/storage">
          <span>
            <span aria-hidden="true">💾</span> Storage &amp; offline books
          </span>
          <span aria-hidden="true">→</span>
        </Link>
        <Link className={styles.linkRow} to="/settings/install">
          <span>
            <span aria-hidden="true">📱</span> Install on iPhone or iPad
          </span>
          <span aria-hidden="true">→</span>
        </Link>
        <Link className={styles.linkRow} to="/admin">
          <span>
            <span aria-hidden="true">🛠️</span> Owner workshop (add &amp; edit books)
          </span>
          <span aria-hidden="true">→</span>
        </Link>
      </section>

      <section className={styles.section} aria-labelledby="s-privacy">
        <h2 id="s-privacy">Privacy</h2>
        <p className={styles.note}>
          Storytime Library is a private, single-owner app. There are no accounts, no
          ads, no tracking, and no analytics. Books you import, your favourites and your
          reading history are stored only on this device. Remember to export a backup
          from the owner workshop — clearing browser data can remove locally stored
          books.
        </p>
      </section>
    </>
  )
}
