/**
 * Curated catalog of public-domain children's books to bundle with the app.
 *
 * Every entry was verified to exist on the mirror by `probe.ts` (see
 * docs/research.md for the run). Editions published before 1930 are in the US
 * public domain; the authors and illustrators named here died well over 70
 * years ago, so these are also public domain in life+70 jurisdictions.
 *
 * `illustrators` is a fallback — the pipeline prefers an "Illustrated by …"
 * credit detected in the edition itself, so books are credited from their own
 * title pages wherever the source states it.
 *
 * `contentNote` records period content worth knowing about. Titles carrying
 * racial slurs or caricature set `hiddenByDefault` with a `contentAdvisory`:
 * they are bundled unedited but kept out of the child-facing library until the
 * owner chooses to show them. That is a suitability decision, kept separate
 * from `rights`, which only describes who may copy the work.
 */

export interface CatalogEntry {
  slug: string
  /** Project Gutenberg title — the mirror's repo name derives from it. */
  title: string
  pgId: number
  repo?: string
  authors: string[]
  illustrators?: string[]
  translators?: string[]
  /** Year of the edition being used. */
  editionYear: number
  publicDomainBasis: string
  description: string
  categories: string[]
  ageRange: '0-3' | '3-5' | '4-8' | '6-10' | 'all-ages'
  readingLevel?: 'pre-reader' | 'early-reader' | 'independent'
  tags?: string[]
  featured?: boolean
  contentNote?: string
  /**
   * Keep the book out of the child-facing library until the owner chooses to
   * show it. Used for period content (racial caricature and the like) — a
   * question of suitability, not of rights.
   */
  hiddenByDefault?: boolean
  contentAdvisory?: string
  /**
   * The owner has read the advisory and chosen to show the book. Required
   * before an advisory book may appear in the library.
   */
  advisoryAcknowledged?: boolean
}

const PD_PRE1930 = 'Published before 1930, so in the public domain in the United States; author and illustrator died more than 70 years ago.'

export const CATALOG: CatalogEntry[] = [
  /* ---------------- Brothers Grimm ---------------- */
  {
    slug: 'household-stories-grimm',
    title: 'Household Stories by the Brothers Grimm',
    pgId: 19068,
    authors: ['Jacob Grimm', 'Wilhelm Grimm'],
    illustrators: ['Walter Crane'],
    translators: ['Lucy Crane'],
    editionYear: 1882,
    publicDomainBasis: PD_PRE1930,
    description:
      'The Grimms’ own collection of household tales in Lucy Crane’s translation, with Walter Crane’s celebrated line illustrations — Snow-White, Rapunzel, Hansel and Gretel, The Bremen Town Musicians and dozens more.',
    categories: ['brothers-grimm', 'fairy-tales', 'classics', 'picture-books'],
    ageRange: '4-8',
    readingLevel: 'early-reader',
    tags: ['grimm', 'walter crane', 'fairy tales', 'illustrated'],
    featured: true,
    contentNote:
      'Authentic Grimm tales: several are dark or violent, as originally recorded. Kept unabridged; hide individual books from the workshop if you prefer.',
  },
  {
    slug: 'grimms-fairy-stories',
    title: "Grimm's Fairy Stories",
    pgId: 11027,
    authors: ['Jacob Grimm', 'Wilhelm Grimm'],
    editionYear: 1922,
    publicDomainBasis: PD_PRE1930,
    description:
      'A generously illustrated early-twentieth-century selection of Grimm tales, including The Goose-Girl, Rumpelstiltskin and The Frog Prince.',
    categories: ['brothers-grimm', 'fairy-tales', 'classics', 'picture-books'],
    ageRange: '4-8',
    readingLevel: 'early-reader',
    tags: ['grimm', 'fairy tales', 'illustrated'],
    contentNote: 'Authentic Grimm tales; several are dark or violent as originally recorded.',
  },

  /* ---------------- Illustrated picture books ---------------- */
  {
    slug: 'tale-of-peter-rabbit',
    title: 'The Tale of Peter Rabbit',
    pgId: 14838,
    authors: ['Beatrix Potter'],
    illustrators: ['Beatrix Potter'],
    editionYear: 1902,
    publicDomainBasis: PD_PRE1930,
    description:
      'Beatrix Potter’s own words and watercolours: Peter squeezes under the gate into Mr McGregor’s garden, and very nearly does not get out again.',
    categories: ['picture-books', 'animals', 'short-reads', 'classics'],
    ageRange: '3-5',
    readingLevel: 'pre-reader',
    tags: ['beatrix potter', 'rabbits', 'garden'],
    featured: true,
  },
  {
    slug: 'a-apple-pie',
    title: 'A Apple Pie',
    pgId: 15809,
    authors: ['Kate Greenaway'],
    illustrators: ['Kate Greenaway'],
    editionYear: 1886,
    publicDomainBasis: PD_PRE1930,
    description:
      'Kate Greenaway’s alphabet picture book — A was an apple pie, and every letter after it brings another crowd of children to the table.',
    categories: ['picture-books', 'poetry-rhymes', 'short-reads'],
    ageRange: '3-5',
    readingLevel: 'pre-reader',
    tags: ['alphabet', 'kate greenaway', 'rhymes'],
  },
  {
    slug: 'a-book-of-nonsense',
    title: 'A Book of Nonsense',
    pgId: 13646,
    authors: ['Edward Lear'],
    illustrators: ['Edward Lear'],
    editionYear: 1894,
    publicDomainBasis: PD_PRE1930,
    description:
      'Edward Lear’s limericks with his own scratchy, joyful drawings. There was an Old Man with a beard… and a hundred more.',
    categories: ['poetry-rhymes', 'funny', 'picture-books', 'classics'],
    ageRange: 'all-ages',
    readingLevel: 'early-reader',
    tags: ['nonsense', 'limericks', 'edward lear'],
    featured: true,
  },
  {
    slug: 'alice-in-wonderland',
    title: "Alice's Adventures in Wonderland",
    pgId: 19033,
    repo: 'Alice-s-Adventures-in-Wonderland_19033',
    authors: ['Lewis Carroll'],
    illustrators: ['John Tenniel'],
    editionYear: 1865,
    publicDomainBasis: PD_PRE1930,
    description:
      'Down the rabbit-hole with Alice, in the edition with John Tenniel’s original engravings — the White Rabbit, the Mad Tea-Party and the Queen of Hearts as they were first drawn.',
    categories: ['classics', 'adventure', 'chapter-books', 'funny'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['alice', 'tenniel', 'wonderland'],
    featured: true,
  },
  {
    slug: 'a-childs-garden-of-verses',
    title: "A Child's Garden of Verses",
    pgId: 25609,
    authors: ['Robert Louis Stevenson'],
    illustrators: ['Jessie Willcox Smith'],
    editionYear: 1905,
    publicDomainBasis: PD_PRE1930,
    description:
      'Stevenson’s poems of childhood — bed in summer, the swing, the lamplighter — with Jessie Willcox Smith’s golden illustrations.',
    categories: ['poetry-rhymes', 'bedtime', 'classics', 'picture-books'],
    ageRange: 'all-ages',
    readingLevel: 'early-reader',
    tags: ['poetry', 'bedtime', 'stevenson'],
    featured: true,
  },
  {
    slug: 'the-green-fairy-book',
    title: 'The Green Fairy Book',
    pgId: 33571,
    authors: ['Andrew Lang'],
    illustrators: ['H. J. Ford'],
    editionYear: 1892,
    publicDomainBasis: PD_PRE1930,
    description:
      'Andrew Lang’s green volume of fairy tales gathered from across Europe, with H. J. Ford’s intricate illustrations.',
    categories: ['fairy-tales', 'classics', 'chapter-books'],
    ageRange: '4-8',
    readingLevel: 'early-reader',
    tags: ['andrew lang', 'fairy tales', 'h j ford'],
  },
  {
    slug: 'indian-fairy-tales',
    title: 'Indian Fairy Tales',
    pgId: 7128,
    authors: ['Joseph Jacobs'],
    illustrators: ['John D. Batten'],
    editionYear: 1892,
    publicDomainBasis: PD_PRE1930,
    description:
      'Folk tales from India retold by Joseph Jacobs, with John D. Batten’s illustrations — including the Panchatantra stories that travelled the world.',
    categories: ['folk-tales', 'fairy-tales', 'classics'],
    ageRange: '4-8',
    readingLevel: 'early-reader',
    tags: ['india', 'folk tales', 'jacobs'],
    contentNote:
      'A Victorian British retelling of Indian folklore; the framing reflects its 1892 origins.',
  },
  {
    slug: 'the-jungle-book',
    title: 'The Jungle Book',
    pgId: 236,
    authors: ['Rudyard Kipling'],
    illustrators: ['John Lockwood Kipling', 'W. H. Drake'],
    editionYear: 1894,
    publicDomainBasis: PD_PRE1930,
    description:
      'Mowgli among the wolves, Rikki-Tikki-Tavi in the garden, and Toomai of the Elephants — Kipling’s jungle stories with the original illustrations.',
    categories: ['classics', 'animals', 'adventure', 'chapter-books'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['kipling', 'mowgli', 'jungle'],
    contentNote:
      'Written in colonial India in 1894; some framing and language reflects that period.',
  },
  {
    slug: 'the-wind-in-the-willows',
    title: 'The Wind in the Willows',
    pgId: 27805,
    authors: ['Kenneth Grahame'],
    editionYear: 1913,
    publicDomainBasis: PD_PRE1930,
    description:
      'Mole, Ratty, Badger and the incorrigible Mr Toad on the River Bank — messing about in boats, and one very stolen motor-car.',
    categories: ['classics', 'animals', 'chapter-books', 'bedtime'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['toad', 'river', 'grahame'],
    featured: true,
  },
  {
    slug: 'the-princess-and-the-goblin',
    title: 'The Princess and the Goblin',
    pgId: 34339,
    authors: ['George MacDonald'],
    editionYear: 1920,
    publicDomainBasis: PD_PRE1930,
    description:
      'Princess Irene finds a mysterious grandmother at the top of the stairs, and a miner’s son named Curdie discovers what the goblins are digging towards.',
    categories: ['fairy-tales', 'adventure', 'chapter-books', 'classics'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['macdonald', 'goblins', 'princess'],
  },
  {
    slug: 'treasure-island',
    title: 'Treasure Island',
    pgId: 120,
    authors: ['Robert Louis Stevenson'],
    editionYear: 1911,
    publicDomainBasis: PD_PRE1930,
    description:
      'Jim Hawkins, the black spot, and Long John Silver — the pirate adventure that invented most of what everyone thinks about pirates.',
    categories: ['adventure', 'classics', 'chapter-books'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['pirates', 'stevenson', 'adventure'],
    contentNote: 'Period adventure novel with pirate violence; best for older children.',
  },
  {
    slug: 'the-adventures-of-tom-sawyer',
    title: 'The Adventures of Tom Sawyer',
    pgId: 74,
    authors: ['Mark Twain'],
    illustrators: ['True Williams'],
    editionYear: 1876,
    publicDomainBasis: PD_PRE1930,
    description:
      'Whitewashing the fence, the graveyard at midnight, and a funeral the boys attend as mourners for themselves.',
    categories: ['classics', 'adventure', 'chapter-books'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['twain', 'mississippi'],
    advisoryAcknowledged: true,
    contentAdvisory:
      'The unabridged 1876 text contains racial slurs and period racial attitudes. It is presented unedited; a grown-up may want to read along or talk it through.',
    contentNote: 'Shown at the owner\u2019s request; carries a content advisory. Rights are clear (public domain).',
  },

  /* ---------------- Text classics (typeset as chapter books) ---------------- */
  {
    slug: 'andersens-fairy-tales',
    title: "Andersen's Fairy Tales",
    pgId: 1597,
    authors: ['Hans Christian Andersen'],
    editionYear: 1872,
    publicDomainBasis: PD_PRE1930,
    description:
      'The Little Mermaid, The Ugly Duckling, The Emperor’s New Clothes and more, from the master of the literary fairy tale.',
    categories: ['andersen', 'fairy-tales', 'classics', 'bedtime'],
    ageRange: '4-8',
    readingLevel: 'early-reader',
    tags: ['andersen', 'fairy tales'],
    featured: true,
  },
  {
    slug: 'fairy-tales-of-hans-christian-andersen',
    title: 'Fairy Tales of Hans Christian Andersen',
    pgId: 27200,
    authors: ['Hans Christian Andersen'],
    editionYear: 1914,
    publicDomainBasis: PD_PRE1930,
    description: 'A second, larger gathering of Andersen’s tales for a long winter of bedtimes.',
    categories: ['andersen', 'fairy-tales', 'classics', 'bedtime'],
    ageRange: '4-8',
    readingLevel: 'early-reader',
    tags: ['andersen', 'fairy tales'],
  },
  {
    slug: 'english-fairy-tales',
    title: 'English Fairy Tales',
    pgId: 7439,
    authors: ['Joseph Jacobs'],
    editionYear: 1890,
    publicDomainBasis: PD_PRE1930,
    description:
      'Jack and the Beanstalk, The Three Little Pigs, Tom Thumb and Henny-Penny, as collected by Joseph Jacobs.',
    categories: ['folk-tales', 'fairy-tales', 'classics'],
    ageRange: '4-8',
    readingLevel: 'early-reader',
    tags: ['england', 'folk tales', 'jacobs'],
  },
  {
    slug: 'celtic-fairy-tales',
    title: 'Celtic Fairy Tales',
    pgId: 7885,
    authors: ['Joseph Jacobs'],
    editionYear: 1892,
    publicDomainBasis: PD_PRE1930,
    description: 'Irish, Scottish and Welsh wonder tales — selkies, giants and the good people.',
    categories: ['folk-tales', 'fairy-tales', 'classics'],
    ageRange: '4-8',
    readingLevel: 'early-reader',
    tags: ['celtic', 'ireland', 'scotland'],
  },
  {
    slug: 'the-blue-fairy-book',
    title: 'The Blue Fairy Book',
    pgId: 503,
    authors: ['Andrew Lang'],
    editionYear: 1889,
    publicDomainBasis: PD_PRE1930,
    description:
      'The first of Lang’s coloured fairy books: Cinderella, Beauty and the Beast, Aladdin and Jack the Giant-Killer.',
    categories: ['fairy-tales', 'classics', 'chapter-books'],
    ageRange: '4-8',
    readingLevel: 'early-reader',
    tags: ['andrew lang', 'fairy tales'],
  },
  {
    slug: 'the-red-fairy-book',
    title: 'The Red Fairy Book',
    pgId: 540,
    authors: ['Andrew Lang'],
    editionYear: 1890,
    publicDomainBasis: PD_PRE1930,
    description: 'Lang’s red volume — Norse, Russian and French tales, including Rapunzel and Jack and the Beanstalk.',
    categories: ['fairy-tales', 'classics', 'chapter-books'],
    ageRange: '4-8',
    readingLevel: 'early-reader',
    tags: ['andrew lang', 'fairy tales'],
  },
  {
    slug: 'the-violet-fairy-book',
    title: 'The Violet Fairy Book',
    pgId: 641,
    authors: ['Andrew Lang'],
    editionYear: 1901,
    publicDomainBasis: PD_PRE1930,
    description: 'Tales from Japan, Serbia, Lithuania and beyond, gathered in Lang’s violet volume.',
    categories: ['fairy-tales', 'classics', 'chapter-books'],
    ageRange: '4-8',
    readingLevel: 'early-reader',
    tags: ['andrew lang', 'fairy tales'],
  },
  {
    slug: 'the-wonderful-wizard-of-oz',
    title: 'The Wonderful Wizard of Oz',
    pgId: 55,
    authors: ['L. Frank Baum'],
    editionYear: 1900,
    publicDomainBasis: PD_PRE1930,
    description:
      'A cyclone carries Dorothy to Oz, where she gathers a scarecrow, a tin woodman and a cowardly lion and walks the yellow brick road.',
    categories: ['classics', 'adventure', 'chapter-books'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['oz', 'baum', 'dorothy'],
    featured: true,
  },
  {
    slug: 'the-marvelous-land-of-oz',
    title: 'The Marvelous Land of Oz',
    pgId: 54,
    authors: ['L. Frank Baum'],
    editionYear: 1904,
    publicDomainBasis: PD_PRE1930,
    description: 'Tip runs away with a pumpkin-headed man and a sawhorse brought to life, and Oz is turned upside down.',
    categories: ['classics', 'adventure', 'chapter-books'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['oz', 'baum'],
  },
  {
    slug: 'through-the-looking-glass',
    title: 'Through the Looking-Glass',
    pgId: 12,
    authors: ['Lewis Carroll'],
    editionYear: 1871,
    publicDomainBasis: PD_PRE1930,
    description: 'Alice steps through the mirror into a country laid out like a chessboard, where the flowers talk back.',
    categories: ['classics', 'adventure', 'chapter-books', 'funny'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['alice', 'carroll'],
  },
  {
    slug: 'peter-pan',
    title: 'Peter Pan',
    pgId: 16,
    authors: ['J. M. Barrie'],
    editionYear: 1911,
    publicDomainBasis: PD_PRE1930,
    description: 'Peter and Wendy, the flight to Neverland, and Captain Hook’s crocodile.',
    categories: ['classics', 'adventure', 'chapter-books'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['barrie', 'neverland'],
    advisoryAcknowledged: true,
    contentAdvisory:
      'The 1911 text depicts Native American characters with slurs and caricature. It is presented unedited; a grown-up may want to read along or talk it through.',
    contentNote: 'Shown at the owner\u2019s request; carries a content advisory. Rights are clear (public domain).',
  },
  {
    slug: 'peter-pan-in-kensington-gardens',
    title: 'Peter Pan in Kensington Gardens',
    pgId: 26999,
    authors: ['J. M. Barrie'],
    editionYear: 1906,
    publicDomainBasis: PD_PRE1930,
    description:
      'The earlier, gentler Peter Pan story: a week-old baby flies out of the nursery window to live among the birds and fairies of Kensington Gardens.',
    categories: ['classics', 'bedtime', 'chapter-books'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['barrie', 'fairies'],
  },
  {
    slug: 'the-secret-garden',
    title: 'The Secret Garden',
    pgId: 113,
    authors: ['Frances Hodgson Burnett'],
    editionYear: 1911,
    publicDomainBasis: PD_PRE1930,
    description:
      'Sour, lonely Mary Lennox finds a key, a walled garden nobody has entered for ten years, and a cousin nobody talks about.',
    categories: ['classics', 'chapter-books'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['garden', 'burnett'],
    featured: true,
  },
  {
    slug: 'little-lord-fauntleroy',
    title: 'Little Lord Fauntleroy',
    pgId: 479,
    authors: ['Frances Hodgson Burnett'],
    editionYear: 1886,
    publicDomainBasis: PD_PRE1930,
    description: 'A kind-hearted boy from New York discovers he is heir to an English earldom, and thaws a very cold grandfather.',
    categories: ['classics', 'chapter-books'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['burnett'],
  },
  {
    slug: 'black-beauty',
    title: 'Black Beauty',
    pgId: 271,
    authors: ['Anna Sewell'],
    editionYear: 1877,
    publicDomainBasis: PD_PRE1930,
    description: 'A horse tells his own life story, from a green meadow to the London cab ranks and home again.',
    categories: ['classics', 'animals', 'chapter-books'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['horses', 'sewell'],
    contentNote: 'Includes frank scenes of animal cruelty — the book was written to campaign against it.',
  },
  {
    slug: 'heidi',
    title: 'Heidi',
    pgId: 1448,
    authors: ['Johanna Spyri'],
    editionYear: 1915,
    publicDomainBasis: PD_PRE1930,
    description: 'An orphan is sent to her grandfather high on an Alp, and quietly changes everyone she meets.',
    categories: ['classics', 'chapter-books', 'bedtime'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['alps', 'spyri'],
  },
  {
    slug: 'the-adventures-of-pinocchio',
    title: 'The Adventures of Pinocchio',
    pgId: 500,
    authors: ['Carlo Collodi'],
    editionYear: 1883,
    publicDomainBasis: PD_PRE1930,
    description: 'A puppet who will not behave, a nose that will not stay put, and a very long road to becoming a real boy.',
    categories: ['classics', 'fairy-tales', 'chapter-books'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['collodi', 'puppet'],
    contentNote: 'The original serial is considerably darker than later adaptations.',
  },
  {
    slug: 'five-children-and-it',
    title: 'Five Children and It',
    pgId: 778,
    authors: ['E. Nesbit'],
    editionYear: 1902,
    publicDomainBasis: PD_PRE1930,
    description: 'Five children dig up a bad-tempered sand-fairy who grants one wish a day — each of which goes wrong by sunset.',
    categories: ['classics', 'funny', 'adventure', 'chapter-books'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['nesbit', 'wishes'],
  },
  {
    slug: 'the-railway-children',
    title: 'The Railway Children',
    pgId: 1874,
    authors: ['E. Nesbit'],
    editionYear: 1906,
    publicDomainBasis: PD_PRE1930,
    description: 'Three children move to a cottage beside the railway line and wave at the 9.15 every morning.',
    categories: ['classics', 'chapter-books'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['nesbit', 'trains'],
  },
  {
    slug: 'at-the-back-of-the-north-wind',
    title: 'At the Back of the North Wind',
    pgId: 225,
    authors: ['George MacDonald'],
    editionYear: 1871,
    publicDomainBasis: PD_PRE1930,
    description: 'A cabman’s son named Diamond is carried through the night sky by the North Wind herself.',
    categories: ['classics', 'bedtime', 'fairy-tales', 'chapter-books'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['macdonald', 'dream'],
  },
  {
    slug: 'the-velveteen-rabbit',
    title: 'The Velveteen Rabbit',
    pgId: 11757,
    authors: ['Margery Williams'],
    editionYear: 1922,
    publicDomainBasis: PD_PRE1930,
    description: 'A stuffed rabbit learns from the old Skin Horse what it takes to become Real.',
    categories: ['classics', 'bedtime', 'short-reads', 'animals'],
    ageRange: '4-8',
    readingLevel: 'early-reader',
    tags: ['toys', 'bedtime'],
    featured: true,
  },
  {
    slug: 'tanglewood-tales',
    title: 'Tanglewood Tales',
    pgId: 976,
    authors: ['Nathaniel Hawthorne'],
    editionYear: 1853,
    publicDomainBasis: PD_PRE1930,
    description: 'Greek myths retold for children — the Minotaur, the dragon’s teeth, and the pomegranate seeds.',
    categories: ['folk-tales', 'classics', 'adventure', 'chapter-books'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['myths', 'greek', 'hawthorne'],
  },
  {
    slug: 'the-second-jungle-book',
    title: 'The Second Jungle Book',
    pgId: 1937,
    authors: ['Rudyard Kipling'],
    editionYear: 1895,
    publicDomainBasis: PD_PRE1930,
    description: 'More of Mowgli’s story, plus the Ankus, the white seal’s ocean and Red Dog.',
    categories: ['classics', 'animals', 'adventure', 'chapter-books'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['kipling', 'mowgli'],
    contentNote: 'Written in colonial India; some framing and language reflects that period.',
  },
  {
    slug: 'just-so-stories',
    title: 'Just So Stories',
    pgId: 2781,
    authors: ['Rudyard Kipling'],
    editionYear: 1902,
    publicDomainBasis: PD_PRE1930,
    description:
      'How the Camel got his Hump, how the Elephant’s Child got his trunk, and how the Alphabet was made — read them aloud.',
    categories: ['classics', 'animals', 'funny', 'bedtime'],
    ageRange: '4-8',
    readingLevel: 'early-reader',
    tags: ['kipling', 'read aloud'],
    featured: true,
    contentNote: 'Written in 1902; occasional period language reflects its origins.',
  },
  {
    slug: 'the-book-of-nonsense-lear',
    title: 'The Book of Nonsense',
    pgId: 982,
    authors: ['Edward Lear'],
    editionYear: 1888,
    publicDomainBasis: PD_PRE1930,
    description: 'A further heap of Lear’s limericks, alphabets and nonsense botany.',
    categories: ['poetry-rhymes', 'funny', 'short-reads'],
    ageRange: 'all-ages',
    readingLevel: 'early-reader',
    tags: ['nonsense', 'edward lear'],
  },
  {
    slug: 'anne-of-green-gables',
    title: 'Anne of Green Gables',
    pgId: 45,
    authors: ['L. M. Montgomery'],
    editionYear: 1908,
    publicDomainBasis: PD_PRE1930,
    description: 'Matthew and Marilla asked for a boy and got Anne Shirley instead — talkative, red-haired and entirely unstoppable.',
    categories: ['classics', 'chapter-books'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['montgomery', 'prince edward island'],
  },
  {
    slug: 'little-women',
    title: 'Little Women',
    pgId: 514,
    authors: ['Louisa May Alcott'],
    editionYear: 1868,
    publicDomainBasis: PD_PRE1930,
    description: 'Meg, Jo, Beth and Amy March grow up through one hard winter and many years after it.',
    categories: ['classics', 'chapter-books'],
    ageRange: '6-10',
    readingLevel: 'independent',
    tags: ['alcott', 'sisters'],
  },
  {
    slug: 'the-tale-of-jemima-puddle-duck',
    title: 'The Tale of Jemima Puddle-Duck',
    pgId: 14814,
    authors: ['Beatrix Potter'],
    editionYear: 1908,
    publicDomainBasis: PD_PRE1930,
    description: 'Jemima wants somewhere quiet to lay her eggs, and a very polite gentleman with sandy whiskers offers his woodshed.',
    categories: ['picture-books', 'animals', 'short-reads', 'classics'],
    ageRange: '3-5',
    readingLevel: 'pre-reader',
    tags: ['beatrix potter', 'ducks'],
  },
]
